version: "3.9"
services:
  dto-django:
    build: .
    restart: always
    ports:
      - "8501:8000"
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    environment:
      - "SECRET_KEY=${SECRET_KEY}"
      - "DJANGO_LOG_FILE=${DJANGO_LOG_FILE}"
      - "DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"
      - "DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL}"
      - "POSTGIS_ADDR=${POSTGIS_ADDR}"
      - "POSTGIS_PORT=${POSTGIS_PORT}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
