version: "3.9"
services:
  dto-django:
    build: .
    image: ghcr.io/dfo-mar-odis/dto:latest
    restart: always
    ports:
      - "80:8000"
    command: /bin/bash entry-point.sh
    volumes:
      - .:/code
    depends_on:
      dto-postgis:
        condition: service_healthy
        
  dto-postgis:
    image: postgis/postgis:13-3.4
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
