version: "3.9"
services:
  dto-django:
    build: .
    restart: always
    ports:
      - "8000:8000"
    command: /bin/bash entry-point.sh
    volumes:
      - .:/code
    depends_on:
      dto-postgis:
        condition: service_healthy
        
  dto-postgis:
    image: postgis/postgis:13-3.4
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - D:\Gov\postgres\dto:/var/lib/postgresql/data/
