version: "3.9"
services:
  dto-nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/opt/project/staticfiles
    depends_on:
      - dto-django

  dto-django:
    build: .
    container_name: dto-django-debug
    restart: always
    ports:
      - "8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
    environment:
      - "SECRET_KEY=${SECRET_KEY}"
      - "DJANGO_LOG_FILE=${DJANGO_LOG_FILE}"
      - "DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"
      - "DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL}"
      - "PGUSER=${PGUSER}"
      - "PGPASSWORD=${PGPASSWORD}"
      - "PGDATABASE=${PGDATABASE}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGIS_ADDR=${POSTGIS_ADDR}"
      - "POSTGIS_PORT=${POSTGIS_PORT}"
    volumes:
      - .:/opt/project
      - static_volume:/opt/project/staticfiles
    depends_on:
      dto-postgis:
        condition: service_healthy

  dto-postgis:
    image: postgis/postgis:13-3.4
    container_name: dto-postgis-debug
    restart: always
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
  static_volume: