version: "3.9"
services:
  dto-django:
    image: ghcr.io/dfo-mar-odis/dto:latest
    restart: always
    ports:
      - "80:8000"
    command: /bin/bash entry-point.sh
    environment:
      - "SECRET_KEY=${SECRET_KEY}"
      - "DJANGO_LOG_FILE=${DJANGO_LOG_FILE}"
      - "DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"
      - "DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL}"
      - "POSTGIS_ADDR=${POSTGIS_ADDR}"
      - "POSTGIS_PORT=${POSTGIS_PORT}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
