# Generated by Django 4.2.13 on 2024-05-16 17:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPAName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_e', models.CharField(max_length=254, null=True)),
                ('name_f', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('mpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries', to='core.mpaname')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.stationlookup')),
            ],
        ),
        migrations.CreateModel(
            name='MPAZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_e', models.CharField(max_length=254, null=True)),
                ('zone_f', models.CharField(max_length=254, null=True)),
                ('url_e', models.CharField(max_length=254, null=True)),
                ('url_f', models.CharField(max_length=254, null=True)),
                ('regulation', models.CharField(max_length=254, null=True)),
                ('reglement', models.CharField(max_length=254, null=True)),
                ('km2', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=102001)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.mpaname')),
            ],
        ),
    ]
