# Generated by Django 4.2.13 on 2024-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='date_time',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
