# Generated by Django 4.2.13 on 2024-06-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_timeseries_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='climatology',
            field=models.FloatField(default=-1, verbose_name='Climatology'),
            preserve_default=False,
        ),
    ]
