# Generated by Django 4.2.13 on 2024-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timeseries_climatology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Common Name')),
                ('scientific_name', models.CharField(max_length=100, unique=True, verbose_name='Scientific Name')),
                ('grouping', models.IntegerField(blank=True, choices=[(1, 'Benthic fish'), (2, 'Benthopelagic fish'), (3, 'Cephalopod'), (4, 'Copepod'), (5, 'Mammal'), (6, 'Pelagic fish'), (7, 'Reptile')], null=True, verbose_name='Grouping')),
                ('importance', models.IntegerField(blank=True, choices=[(1, 'Commercial'), (2, 'Important food source')], null=True, verbose_name='Importance')),
                ('status', models.IntegerField(choices=[(1, 'Extinct'), (2, 'Extinct in the Wild'), (3, 'Critically Endangered'), (4, 'Endangered'), (5, 'Vulnerable'), (6, 'Near Threatened'), (7, 'Least Concern'), (8, 'Data Deficient'), (9, 'Not Evaluated')], default=9, verbose_name='Status')),
                ('lower_temperature', models.FloatField(verbose_name='Lower Temperature')),
                ('upper_temperature', models.FloatField(verbose_name='Upper Temperature')),
                ('lower_depth', models.FloatField(verbose_name='Lower Depth')),
                ('upper_depth', models.FloatField(verbose_name='Upper Depth')),
            ],
        ),
    ]
