# Generated by Django 4.2.16 on 2024-10-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='depth',
            field=models.IntegerField(null=True, verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='species',
            name='grouping',
            field=models.IntegerField(blank=True, choices=[(1, 'Benthic fish'), (2, 'Benthopelagic fish'), (3, 'Benthic Invertebrates'), (4, 'Cephalopod'), (5, 'Copepod'), (6, 'Mammal'), (7, 'Pelagic fish'), (8, 'Reptile')], null=True, verbose_name='Grouping'),
        ),
    ]
