# Generated by Django 4.2.16 on 2025-04-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timeseries_depth_alter_species_grouping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpazone',
            name='reglement',
        ),
        migrations.RemoveField(
            model_name='mpazone',
            name='regulation',
        ),
        migrations.RemoveField(
            model_name='mpazone',
            name='zone_e',
        ),
        migrations.RemoveField(
            model_name='mpazone',
            name='zone_f',
        ),
    ]
