# Generated by Django 4.2.20 on 2025-05-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_indicator_remove_timeseries_climatology_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseries',
            old_name='temperature',
            new_name='value',
        ),
    ]
