# Generated by Django 4.2.20 on 2025-05-01 14:24

from django.db import migrations, models
import django.db.models.deletion


# for the purposes of adding the indicator field to the timeseries the timeseries lookup needs to have
# at least one value in it. At the time of development we only have temperature as an indicator so
# it makes sense to have the first indicator as temperature
def add_default_indicators(apps, schema_editor):
    Indicator = apps.get_model('core', 'Indicator')
    if not Indicator.objects.filter(pk=1).exists():
        Indicator(1, 'Temperature').save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_temperature_timeseries_value'),
    ]

    operations = [
        migrations.RunPython(add_default_indicators, None),

        migrations.AddField(
            model_name='timeseries',
            name='indicator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timeseries', to='core.indicator'),
            preserve_default=False,
        ),
    ]
