# Generated by Django 4.2.23 on 2025-06-10 18:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_timeseries_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPAZones',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_e', models.CharField(max_length=254, null=True)),
                ('name_f', models.CharField(max_length=254, null=True)),
                ('url_e', models.CharField(max_length=254, null=True)),
                ('url_f', models.CharField(max_length=254, null=True)),
                ('km2', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='MPAZone',
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='mpa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries', to='core.mpazones'),
        ),
        migrations.DeleteModel(
            name='MPAName',
        ),
    ]
