# Generated by Django 4.2.23 on 2025-06-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mpazones_delete_mpazone_alter_timeseries_mpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_e', models.CharField(max_length=254, verbose_name='Classification Name (English)')),
                ('name_f', models.CharField(max_length=254, verbose_name='Classification Name (French)')),
            ],
        ),
        migrations.RenameModel(
            old_name='Indicator',
            new_name='Indicators',
        ),
        migrations.AddField(
            model_name='mpazones',
            name='classification',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
