# Generated by Django 4.2.23 on 2025-06-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_classifications_rename_indicator_indicators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifications',
            name='name_e',
            field=models.CharField(max_length=50, verbose_name='Classification Name (English)'),
        ),
        migrations.AlterField(
            model_name='classifications',
            name='name_f',
            field=models.CharField(max_length=50, verbose_name='Classification Name (French)'),
        ),
        migrations.AlterField(
            model_name='mpazones',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.classifications'),
        ),
    ]
