# Generated by Django 4.2.23 on 2025-06-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_classifications_name_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifications',
            name='colour',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Classification Colour'),
        ),
    ]
