# Generated by Django 4.2.23 on 2025-08-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_classifications_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseries',
            old_name='mpa',
            new_name='zone',
        ),
    ]
