# Generated by Django 4.2.23 on 2025-08-07 13:44

from django.db import migrations, models
import django.db.models.deletion


def create_initial_climatemodel(apps, schema_editor):
    ClimateModels = apps.get_model('core', 'ClimateModels')
    ClimateModels.objects.create(id=1, name='GLORYS', priority=0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_mpa_timeseries_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Climate Name')),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(create_initial_climatemodel),
        migrations.AddField(
            model_name='timeseries',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timeseries', to='core.climatemodels'),
            preserve_default=False,
        ),
    ]
