# Generated by Django 4.2.23 on 2025-08-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_climatemodels_timeseries_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(verbose_name='Date')),
                ('depth', models.IntegerField(verbose_name='Depth')),
                ('value', models.FloatField(verbose_name='Value')),
                ('count', models.IntegerField(help_text='Number of observations recorded at a depth for a specific date and location', verbose_name='Count')),
                ('std', models.FloatField(verbose_name='Standard Deviation')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.indicators')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.mpazones')),
            ],
        ),
    ]
