# Generated by Django 4.2.23 on 2025-08-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpazones',
            name='serialized_representation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climatemodels',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Model Name'),
        ),
    ]
