# Generated by Django 4.2.23 on 2025-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_mpazones_serialized_representation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='type',
            field=models.IntegerField(choices=[(1, 'BOTTOM'), (2, 'SURFACE')], default=1),
        ),
    ]
