# Generated by Django 4.2.23 on 2025-08-26 13:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_timeseries_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnsetOfSpringAnomalies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Year')),
                ('anomaly', models.FloatField(verbose_name='Anomaly')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onsets', to='core.climatemodels')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onsets', to='core.mpazones')),
            ],
        ),
    ]
