# Generated by Django 4.2.23 on 2025-09-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_onsetofspringanomalies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indicators',
            new_name='TimeseriesVariables',
        ),
    ]
