# Generated by Django 4.2.23 on 2025-09-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_indicators_timeseriesvariables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnsetOfSpringAnomalies',
            new_name='Indicators',
        ),
    ]
