# Generated by Django 4.2.23 on 2025-09-10 18:05

from django.db import migrations, models
import django.db.models.deletion


def add_default_indicator_type(apps, schema_editor):
    IndicatorTypes = apps.get_model('core', 'IndicatorTypes')
    IndicatorTypes.objects.create(name='Onset of Spring', description='Yearly onset of spring anomaly')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_onsetofspringanomalies_indicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Indicator Type')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
        ),
        migrations.RunPython(add_default_indicator_type, reverse_code=lambda apps, schema_editor: None),
        migrations.RemoveField(
            model_name='indicators',
            name='anomaly',
        ),
        migrations.AddField(
            model_name='indicators',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='core.climatemodels'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='core.mpazones'),
        ),
        migrations.AddField(
            model_name='indicators',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='core.indicatortypes'),
            preserve_default=False,
        ),
    ]
