# Generated by Django 4.2.23 on 2025-09-12 13:14

from django.db import migrations, models
import django.db.models.deletion

def add_default_indicator_category(apps, schema_editor):
    IndicatorCategories = apps.get_model('core', 'IndicatorCategories')
    IndicatorCategories.objects.create(name='Unknown', description='Indicator not yet categorized')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_indicatortypes_remove_indicators_anomaly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Indicator Category')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
        ),
        migrations.RunPython(add_default_indicator_category, reverse_code=lambda apps, schema_editor: None),
        migrations.AlterField(
            model_name='indicators',
            name='value',
            field=models.FloatField(default=0, verbose_name='Value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicatortypes',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Indicator Type'),
        ),
        migrations.CreateModel(
            name='IndicatorWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1, verbose_name='Indicator Weight')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_weights', to='core.indicatortypes')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_weights', to='core.mpazones')),
            ],
        ),
        migrations.AddField(
            model_name='indicatortypes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_types', to='core.indicatorcategories'),
            preserve_default=False,
        ),
    ]
