# Generated by Django 4.2.23 on 2025-09-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_indicatorcategories_alter_indicators_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortypes',
            name='unit',
            field=models.CharField(default='Standardized Anomalies (σ)', max_length=45, verbose_name='Indicator Unit'),
            preserve_default=False,
        ),
    ]
