# Generated by Django 4.2.23 on 2025-10-07 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_indicatortypes_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.FloatField()),
                ('bottom', models.FloatField()),
                ('right', models.FloatField()),
                ('left', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.climatemodels')),
            ],
        ),
    ]
