# Generated by Django 4.2.23 on 2025-10-07 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_areaofinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofinterest',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_of_interest', to='core.climatemodels'),
        ),
    ]
