# Generated by Django 4.2.23 on 2025-11-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_areaofinterest_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorRamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ramp Name')),
            ],
        ),
        migrations.CreateModel(
            name='SpatialRasterSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Formal name of the data')),
                ('label', models.CharField(max_length=50, verbose_name='Short informal label to use for the dataset')),
                ('description', models.CharField(max_length=255, verbose_name='Description of the dataset')),
                ('units', models.CharField(max_length=20, verbose_name='Units of the dataset')),
                ('precision', models.IntegerField(default=2, verbose_name='Precision of the dataset')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raster_sets', to='core.colorramps', verbose_name='Color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raster_sets', to='core.climatemodels', verbose_name='Climate Model')),
            ],
        ),
        migrations.CreateModel(
            name='SpatialReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.CharField(max_length=255, verbose_name='Citation')),
                ('spatial_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.spatialrastersets', verbose_name='Spatial raster set')),
            ],
        ),
        migrations.CreateModel(
            name='Rasters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Order of the raster')),
                ('filename', models.CharField(max_length=100, verbose_name='Filename')),
                ('spatial_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasters', to='core.spatialrastersets', verbose_name='Spatial raster set')),
            ],
        ),
    ]
