# Generated by Django 4.2.23 on 2025-11-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_colorramps_spatialrastersets_spatialreferences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rasters',
            old_name='filename',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='rasters',
            name='label',
            field=models.CharField(default='img1', max_length=50, verbose_name='Label of the raster'),
            preserve_default=False,
        ),
    ]
