# Generated by Django 4.2.23 on 2025-11-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_filename_rasters_file_name_rasters_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rasters',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='spatialrastersets',
            name='description',
            field=models.TextField(verbose_name='Description of the dataset'),
        ),
    ]
