name: Build and Push DTO Image to GitHub Container Registry (GHCR)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # standard actions/checkout to checkout the repo to the virtual machine
      - name: Checkout repository
        uses: actions/checkout@v3

      # use the setup-qemu-action https://github.com/docker/setup-qemu-action?tab=readme-ov-file#about
      # to create and build a QEMU the virtual machine https://github.com/qemu/qemu?tab=readme-ov-file#qemu-readme
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # use the setup-buildx-action https://github.com/docker/setup-buildx-action?tab=readme-ov-file#about
      # to build the docker image on the virtual machine
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # use the build-push-action https://github.com/docker/build-push-action?tab=readme-ov-file#about
      # to put it all together and save the resulting image from the current virtual machine
      # > tags: ghcr.io/<gchr user account>/<image name>:(<version>|latest)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/dfo-mar-odis/dto:latest

      - name: Logout of GitHub Container Registry
        run: docker logout ghcr.io